{% set name = "pyclipper" %}
{% set version = "1.4.0" %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyclipper-{{ version }}.tar.gz
  sha256: 9882bd889f27da78add4dd6f881d25697efc740bf840274e749988d25496c8e1

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<310]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
  host:
    - python
    - cython >=0.28
    - pip
    - setuptools
    - setuptools_scm
    - wheel
  run:
    - python

test:
  source_files:
    - tests
  imports:
    - pyclipper
  commands:
    - pip check
    - pytest -v tests
  requires:
    - pip
    - pytest

about:
  home: https://github.com/fonttools/pyclipper
  # See Boost Sowtfare License https://github.com/fonttools/pyclipper/tree/main#license
  license: MIT and BSL-1.0
  license_family: MIT
  license_file: 
    - LICENSE
    - LICENSE.txt
  summary: "Cython wrapper for the C++ translation of the Angus Johnson's Clipper library (ver. 6.4.2)"

  description: |
    "Pyclipper is a Cython wrapper exposing public functions and classes of the C++ 
     translation of the Angus Johnson’s Clipper library (ver. 6.4.2)."
  dev_url: https://github.com/fonttools/pyclipper
  doc_url: https://github.com/fonttools/pyclipper#readme

extra:
  recipe-maintainers:
    - jakakokosar
