travis:
  secure:
    BINSTAR_TOKEN: KOEKfIjyLmWbte0bMysokVU6Pt1up4PkLnoksQXx/4xVvyJVb5Y4SZA58szqisZ9/6+fA+o5wrr4Fqe3yRl0O9yl4d1r4IE7eutRddaQkk3Peo/HJkdQTmM2SQ9sqKLxClfbMdwztE5V2O30dMfKZTdzR/djxJ1HXa/NEZt7gSx70v1OtZKuUrmUp1PfQXXkk3PZtlm2sDXR7gfI+WIGFLNUcuJ5qBpndMANPIo30DBvVo0OBbbNTWkR3j1Gxyi1MwYan7yiU87MEpB7jM7WTtIAOqOgGwq0uiTs2dBMA8SddT6jwoMSUPUlrf3dsZEKBBZ2fYqsYq9iGFdglCn7NNgk3a/uZc7UvR7t1XTJi6UfmhW7qC50IoDNWiDQjOpbMaosjpiBWxppEeKIZ01Hk85hIfjL2Ufm9DBAdM75KImQLATWlsdYiihlIiJ1hlYbgT0JNAMc9Oj89dz2FdGe8BSF33ZNVcCcyxpMws+d95Fkl/jGixI0tv3sHtJKdjSggd8cFoNekIZYZ0Iblw+wtp7N6YQo6Cv40p19vmYmp5rQUFtrachdUSgIP4Ge7rSwmmCg2KqR9nOXrqWxS1244+x+uWifG2I/fy/vscH5JX/c6s7iFr4sgSJPttmvfEC1JwOsyndK+Bew70ADUSWslPdZx0eI0j9BIwBwIRCWsKU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
